server:
  port: 8082


# Internationalization
spring:
  messages:
    basename: messages/messages
  jpa:
    hibernate:
      ddl-auto: validate
  profiles:
    active: jpa

#  h2:
#    console:
#      enabled: true
